import{a as v,S as w,i as a}from"./assets/vendor-B5nsgUv9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&c(u)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const P="54665036-94176af4f08ccc0fd35b37209",S="https://pixabay.com/api/",E=15;async function f(o,e){const r={key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:E},{data:c}=await v.get(S,{params:r});return c}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),p=document.querySelector(".load-more"),M=new w(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const e=o.map(r=>`
      <li class="photo-card">
        <a class="gallery-link" href="${r.largeImageURL}" rel="noopener noreferrer">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
          <div class="info">
            <p class="info-item">Likes <span>${r.likes}</span></p>
            <p class="info-item">Views <span>${r.views}</span></p>
            <p class="info-item">Comments <span>${r.comments}</span></p>
            <p class="info-item">Downloads <span>${r.downloads}</span></p>
          </div>
        </a>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",e),M.refresh()}function $(){m.innerHTML=""}function g(){y.classList.remove("is-hidden")}function L(){y.classList.add("is-hidden")}function b(){p.classList.remove("is-hidden")}function d(){p.classList.add("is-hidden")}const B=document.querySelector(".form"),R=document.querySelector(".search-input"),A=document.querySelector(".load-more");let l="",i=1,n=0;const q=15;d();B.addEventListener("submit",O);A.addEventListener("click",_);async function O(o){if(o.preventDefault(),l=R.value.trim(),i=1,n=0,$(),d(),!l){a.info({message:"Please enter a search query."});return}try{g();const e=await f(l,i);if(n=e.totalHits,!e.hits.length){a.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(e.hits),Math.ceil(n/q)<=1?(d(),a.info({message:"We're sorry, but you've reached the end of search results."})):b(),a.success({message:`Hooray! We found ${n} images.`})}catch{a.error({message:"Request failed. Try again later."})}finally{L()}}async function _(){i+=1,d(),g();try{const o=await f(l,i);h(o.hits),H();const e=Math.ceil(n/q);i>=e?a.info({message:"We're sorry, but you've reached the end of search results."}):b()}catch{a.error({message:"Request failed. Try again later."})}finally{L()}}function H(){const o=document.querySelector(".gallery a");if(!o)return;const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
