import{a as S,S as b,i as a}from"./assets/vendor-B5nsgUv9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const v="54665036-94176af4f08ccc0fd35b37209",E="https://pixabay.com/api/",P=15;async function f(r,e){const o={key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:P},{data:c}=await S.get(E,{params:o});return c}const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more"),M=new b(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const e=r.map(o=>`
      <li class="photo-card">
        <a class="gallery-link" href="${o.largeImageURL}" rel="noopener noreferrer">
          <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
          <div class="info">
            <p class="info-item">Likes <span>${o.likes}</span></p>
            <p class="info-item">Views <span>${o.views}</span></p>
            <p class="info-item">Comments <span>${o.comments}</span></p>
            <p class="info-item">Downloads <span>${o.downloads}</span></p>
          </div>
        </a>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",e),M.refresh()}function $(){m.innerHTML=""}function g(){p.classList.remove("is-hidden")}function L(){p.classList.add("is-hidden")}function B(){y.classList.remove("is-hidden")}function u(){y.classList.add("is-hidden")}const q=document.querySelector(".form"),R=document.querySelector(".search-input"),A=document.querySelector(".load-more");let l="",n=1,i=0;const w=15;u();q.addEventListener("submit",O);A.addEventListener("click",_);async function O(r){if(r.preventDefault(),l=R.value.trim(),n=1,i=0,$(),u(),!l){a.info({message:"Please enter a search query."});return}try{g();const e=await f(l,n);if(i=e.totalHits,!e.hits.length){a.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(e.hits);const o=Math.ceil(i/w);n<o&&B(),a.success({message:`Hooray! We found ${i} images.`})}catch{a.error({message:"Request failed. Try again later."})}finally{L(),q.reset()}}async function _(){n+=1;try{g();const r=await f(l,n);h(r.hits),H();const e=Math.ceil(i/w);n>=e&&(u(),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({message:"Request failed. Try again later."})}finally{L()}}function H(){const r=document.querySelector(".gallery a");if(!r)return;const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
